In [9]:
import pandas as pd
def read_file(filepathe):
    return pd.read_csv(filepathe)
df=read_file("Titanic.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [6]:
import importlib
import prepr

importlib.reload(prepr)

In [7]:
from config import cols_drop
from prepr import drop_cols,get_infoo

In [8]:
df = drop_cols(df,cols_drop)

KeyError: "['PassengerId', 'Name', 'Ticket'] not found in axis"

In [10]:
get_infoo(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
nunique,891,2,3,891,2,88,7,7,681,248,147,3
dtype,int64,int64,int64,str,str,float64,int64,int64,str,float64,str,str

In [ ]:
null = df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       3
Embarked    0
dtype: int64

In [11]:
df = df.dropna(subset={"Emparked"})

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [12]:
df = drop_cols(df,"Pclass")

In [13]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived                                               Name  \
0              1         0                            Braund, Mr. Owen Harris
1              2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3         1                             Heikkinen, Miss. Laina
3              4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5         0                           Allen, Mr. William Henry
..           ...       ...                                                ...
886          887         0                              Montvila, Rev. Juozas
887          888         1                       Graham, Miss. Margaret Edith
888          889         0           Johnston, Miss. Catherine Helen "Carrie"
889          890         1                              Behr, Mr. Karl Howell
890          891         0                                Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S
1    female  38.0      1      0          PC 17599  71.2833   C85        C
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3    female  35.0      1      0            113803  53.1000  C123        S
4      male  35.0      0      0            373450   8.0500   NaN        S
..      ...   ...    ...    ...               ...      ...   ...      ...
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

[891 rows x 11 columns]>

In [14]:
df

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q